//**********************************************************************************************
//
//    Copyright (c) 1993 Axon Instruments.
//    All rights reserved.
//
//**********************************************************************************************
// HEADER:  WINCPP.HPP
// PURPOSE: Contains common includes. Used for generation of precompiled headers.
// AUTHOR:  BHI  Nov 1993
//

#include "..\common\axodefn.h"
#include "..\common\axodebug.h"
#include "..\common\colors.h"
#include "..\common\adcdac.h"
#include <stdio.h>   
#include <stdlib.h>  
#include <ctype.h>  
#include <limits.h>
#include <memory.h>  
#include <string.h>
#include <math.h>


