//***********************************************************************************************
//
//    Copyright (c) 1993-1997 Axon Instruments.
//    All rights reserved.
//    Permission is granted to freely to use, modify and copy the code in this file.
//
//***********************************************************************************************
// HEADER:  wincpp.hpp
// PURPOSE: Contains common includes. Used for generation of precompiled headers.
// AUTHOR:  BHI  Nov 1993
//

#include "..\common\axodefn.h"
#include "..\common\axodebug.h"
#include "..\common\colors.h"
#include "..\common\adcdac.h"

#include <stdio.h>   
#include <stdlib.h>  
#include <limits.h>
#include <memory.h>  
#include <string.h>
#include <math.h>
#include <ctype.h>


