//***********************************************************************************************
//
//    Copyright (c) 1993 Axon Instruments.
//    All rights reserved.
//
//***********************************************************************************************
// MODULE:  WINCPP.C
// PURPOSE: Used to create preprocessed header.
// AUTHOR:  BHI  Nov 1993
//

#include "wincpp.hpp"
