//***********************************************************************************************
//
//    Copyright (c) 1993-1997 Axon Instruments.
//    All rights reserved.
//    Permission is granted to freely to use, modify and copy the code in this file.
//
//***********************************************************************************************
// MODULE:  WINCPP.C
// PURPOSE: Used to create preprocessed header.
// AUTHOR:  BHI  Nov 1993
//

#include "wincpp.hpp"
